<?php

/**
 * @var \Redepy\HelloWorld\Block\Display $block
 */

?>

<html>
<head>
    <meta charset="utf-8">
</head>
<body>
<form action="/helloworld/test/save" method="post">
    <p><select name="id">
            <option disabled>Выберите продукт</option>
            <?php foreach ($block->getProductCollection() as $product): ?>
                <option value="<?php echo $product->getId() ?>"><?php echo $product->getName() ?></option>
            <?php endforeach; ?>
        </select></p>
    Text:<br>
    <input type="text" name="text">
    <br><br>
    <input type="submit" value="Submit">
</form>
</body>
</html>
